---
title: "María Nanton - CV"
editor: visual
---

## Overview

## Selected work experience

### Health Information and Statistics Office. Buenos Aires City Ministry of Health.

**Head of Data Science (2023 - present)**

-   Management of 15+ data analyst and data scientists
-   Responsible for overseeing and driving strategic decision-making at the Office level (team with 30+ members)
-   Direct coordination of Data Analysis and Data Science projects

**Data Analyst (2020 - 2023)**

-   Analysis and processing of databases using R and SQL.
-   Development of complex algorithms and coordination of applied Machine Learning projects.
-   Design, development, and delivery of data-based digital products.
-   Redesign of workflows at the for digital product development.
-   Design and implementation of data quality and integrity validation processes.

### iMettrics

**Data Analyst (2010 - 2020)** 

-   Reporting and Insights Analyst - Digital Performance Analytics. 
-   Responsible for creating dashboards, presenting reports to clients, and performing on-demand analysis.
-   Collaboration in the formulation of measurement strategies and data analysis based on tactical and strategic objectives.

## Selected education

**M.S., Data Mining (in progress)**

-   School of Exact and Natural Sciences

-   University of Buenos Aires

**B.S., Social Communication (2019)**

-   School of Social Sciences

-   University of Buenos Aires

## Selected teaching experience

**Advanced Statistics Assistant Professor (2024 - present)** - Italian Hospital University Institute, M.S. in Clinical Research

**Instructor (2021)** - The Carpentries

**Data Science Instructor (2019 - 2021)** - Argentine School of New Technologies (EANT)

**Lead Instructor (2019 - present)** - R programming, data analysis and visualization courses

## Selected community developments

**MetaDocencia - Infrastructure Developer and Instructor (2023 - present)**

MetaDocencia is an organization committed to advancing Open Science practices across Latin America and the Caribbean. Its work focuses on capacity-building, adapting and creating educational resources in Spanish, and fostering a network of regional communities and stakeholders. Currently, it is part of the NASA TOPS initiative and serves as the contextualizer for NASA materials in Spanish.

**R-Ladies Buenos Aires - organizer/Instructor (2019 - present)**

R-Ladies is an international initiative dedicated to promoting diversity and inclusion within the R programming community. The Buenos Aires chapter organizes 3 to 6 events annually, featuring activities such as technical skill-building workshops, short presentations by members and guest speakers, as well as community-building and networking opportunities.

**LatinR - organizer committee (2021, 2023)**

Latin American Conference about the Use of R for Research + Development

## Selected awards and scholarships

**KHIPU 2023**

-   *Latin American Meeting in Artificial Intelligence, Montevideo, Uruguay* Selected to participate in this highly competitive event, recognized for academic excellence and contributions to diversity in AI research.

**Posit Opportunity Scholarship (2023)**

-   *Posit::conf(2023), Chicago, USA* Awarded funding to attend the Posit Conference 2023. Covered travel, accommodation, meals, and conference fees.
